### ISSUE TITLE
TP2 Aprobado: 8 (Ocho)

### ISSUE THREAD

**Issue by egenender** [V-SANT/TDA_2024_1C#2]
La calidad del trabajo es muy buena y el nivel de detalle de las descripciones en casi todas las secciones hizo muy placentero de leer el trabajo.

La reducción de nota en este caso para un trabajo que de otra manera sería excelente, se debe a los 2 puntos del enunciado que solicitan el análisis de Variabilidad de los Valores, que entiendo que no se le prestó la atención debido al desafío que los puntos plantean.

Aquí les dejo todos los comentarios:

> E - Lista de Carga de Energía de los Dai Li

La condición de monótona creciente también se puede expresar matemáticamente

> Debido a la naturaleza combinatoria del problema, una manera de encararlo es utilizar el
> enfoque de programación dinámica.

Suma aclarar de dónde proviene esa naturaleza combinatoria, y es que en cada minuto se puede tomar la decisión de cargar o atacar, lo cual resulta en un espacio exponencial de posibles soluciones.

> Con esta idea, se puede inferir que en un ataque de cualquier tamaño, los Dai Li atacarán al
> menos una vez pues ese valor será mayor a cero.

Aquí mismo se podría desprender que atacar en el último minuto siempre es conveniente, ya que no tiene sentido cargar para un ataque que no existirá.
Esta observación sí esta presente después

>  Tanto para construir la estrategia
> óptima como para calcular la cantidad total de enemigos eliminados, se debe iterar cada minuto
> una sola vez. Para la primera, se itera de forma descentente y para la segunda de forma ascendente.
> Ambas secciones tienen entonces una complejidad de O(n).

Se puede aclarar que en cada paso de la iteración se hacen operaciones de orden constante

> Variabilidad de Valores

Esto es algo a analizar tanto desde el punto de optimalidad como de complejidad algorítmica.

Para la optimalidad, si se quiere demostrar se requeriría un análisis del tipo inductivo.

Para la complejidad, es necesario pensar si los valores afectan a la complejidad. Se interpreta a nivel teórico que al depender únicamente de n, que no debería afectar. Pero luego corresponde hacer el análisis empírico variando los valores para verificarlo.
Por otro lado, dependiendo de cómo se haga la reconstrucción, la cantidad de ataques o cargas puede afectar la complejidad y eso sería un caso de variabilidad. En su solución esto no afecta, pero sí debería incluirse el por qué en el análisis.

> Mediciones Temporales

Como les comenté en el tp1, en este caso hay dos secciones de algoritmo bien marcadas, la búsqueda de los valores óptimos y la reconstrucción. Siendo que la solución tiene varias partes, habría que hacer un análisis empírico de una y otra por separado.

**Comment by V-SANT** [comment]
Hola Ezequiel,
Muchas gracias por el feedback. Lo vamos a tener en cuenta para el TP3.
Saludos
