### ISSUE TITLE
TP3 Aprobado: 9 (Nueve)

### ISSUE THREAD

**Issue by egenender** [V-SANT/TDA_2024_1C#3]
> Demostración: Multiway Partition Problem es NP Completo usando
> Subset Sum Problem

La demostración de que Multiway Partition Problem es NP Completo también es una muestra de que el **2-way Partition Problem** es NP Completo, también conocido como Partition Problem.
Justamente porque la cantidad de subconjuntos que se le pidió a Multiway es 2, por ello es 2-way.

```
    if index == len(maestros):
        coeficiente_actual = calcular_coeficiente(sumas)
        if coeficiente_actual < mejor_solucion[0]:
            # Sobreescribo mi mejor solucion con todos los maestros asignados
            mejor_solucion[0] = coeficiente_actual
            # Pongo como quedaría mi mejor solución
            mejor_solucion[1] = [list(grupo) for grupo in grupos]
        # Siempre voy a querer retornear para que se sigan calculando las otras opciones
        return
```

El cálculo de coeficiente de sumas es un valor que puede mantenerse a través del algoritmo, sumando y restando en O(1) el valor que se altera, para evitar hacer cada vez la iteración que requiere la suma.
Es recomendable que la función devuelva el resultado, la modificación que se hace a "mejor_solucion" es una especie de _hack_ que funciona pero no recomendamos

```
    for maestro in maestros_ordenados:
        grupo_minimo = grupos.pop(0)
        nuevo_valor = grupo_minimo[1] + maestro[1]
        maestros_grupo = grupo_minimo[0] + [maestro[0]]
        grupo_minimo = (maestros_grupo, nuevo_valor)

        grupos = insertar_ordenado(grupos, grupo_minimo)
```

La implementación de Greedy también se puede optimizar con el uso de Heap

> La complejidad total de este algoritmo es la resultante
> de, ordenar a los maestros por habilidades O(m.log(m)), luego, que por cada iteración de los maestros
> O(m), se reubique al grupoM in modificado en la posición correspondiente a la habilidad acumulada
> O(k), por lo que la complejidad de este algoritmo es O(m.k) + O(m.log(m)).

Si la complejidad está bien definida, entonces corresponde utilizar Heap.
Eso queda ya supeditado a la investagación del módulo bisect

> A partir del valor de las relaciones, se puede inferir que tanto se aleja de la solución óptima. Se
> realizaron mediciones para 50 instancias aleatorias con una cantidad menor o igual a 12 maestros con
> un rango de habilidad de 1 a 1000 y con la cantidad de grupos constante. Para cada instancia, se corre
> el algoritmo Greedy y el algoritmo de backtracking que obtiene la solución óptima. Luego se divide el
> resultado aproximando entre el óptimo y se toma ese punto del gráfico.

Notar que también se pueden construir instancias cuya solución sea, por construcción, conocida, sin tener que recurrir al algoritmo de Backtracking.

> Como se puede apreciar, el algoritmo tiene una cota de error cercana al 0.0025 lo que indica que el
> algoritmo Greedy tiene un error aproximado al 0.3 %. Aunque no siempre obtiene el resultado correcto,
> sigue siendo útil pues da un valor aproximado en un tiempo considerablemente menor

Podría hacerse un análisis para generar una instancia que sea particularmente complicada de resolver para el conocido algoritmo Greedy

> Para completar el análisis, se analizará otra estrategia Greedy. El algoritmo es el siguiente: Calcular
> la suma total de las habilidades de todos los maestros y dividirla por la cantidad de grupos, dando
> una SumaHabilidadIdeal. Luego, Ordenar de mayor a menor los maestros en función de su habilidad
> o fortaleza. Iterar los grupos de manera circular (si se llega al último grupo, se comienzan a iterar
> nuevamente desde el principio) e ir colocando un maestro por cada iteración. Si la suma acumulada de
> fuerza de un grupo supera la SumaHabilidadIdeal, se saltea.

La descripción omite qué ocurre cuando, con toda probabilidad, suceda la situación de que el maestro, sin importar dónde se ubique, excederá la SumaHabilidadIdeal

**Comment by V-SANT** [comment]
Buenísimo Ezequiel. Muchas gracias!
